language: android
sudo: true
android:
  components:
    - tools
    - platform-tools

    - build-tools-23.0.3
    - android-23

    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+
script:
  - chmod +x ./gradlew
  # By default Travis-ci executes './gradlew build connectedCheck' if no 'script:' section found.
  - ./gradlew build